"""initial schema

Revision ID: 096466e69945
Revises: 
Create Date: 2026-05-21 18:12:59.913625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '096466e69945'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_categories',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=30), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('code'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('customers',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index('idx_customers_name', ['name'], unique=False)
        batch_op.create_index('idx_customers_phone', ['phone'], unique=False)

    op.create_table('pets',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('species', sa.String(length=20), nullable=True),
    sa.Column('breed', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.create_index('idx_pets_customer', ['customer_id'], unique=False)

    op.create_table('cost_records',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('pet_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('category_code', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('cost_records', schema=None) as batch_op:
        batch_op.create_index('idx_costs_category', ['category_code'], unique=False)
        batch_op.create_index('idx_costs_occurred', ['occurred_on'], unique=False)
        batch_op.create_index('idx_costs_pet_date', ['pet_id', 'occurred_on'], unique=False)

    # ### end Alembic commands ###

    cost_categories_table = sa.table(
        'cost_categories',
        sa.column('code', sa.String(length=30)),
        sa.column('label', sa.String(length=30)),
        sa.column('sort_order', sa.Integer()),
    )
    op.bulk_insert(
        cost_categories_table,
        [
            {"code": "food", "label": "粮食", "sort_order": 10},
            {"code": "medical", "label": "医疗", "sort_order": 20},
            {"code": "grooming", "label": "美容", "sort_order": 30},
            {"code": "toy", "label": "玩具", "sort_order": 40},
            {"code": "other", "label": "其他", "sort_order": 99},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        "DELETE FROM cost_categories WHERE code IN ('food','medical','grooming','toy','other')"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cost_records', schema=None) as batch_op:
        batch_op.drop_index('idx_costs_pet_date')
        batch_op.drop_index('idx_costs_occurred')
        batch_op.drop_index('idx_costs_category')

    op.drop_table('cost_records')
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_index('idx_pets_customer')

    op.drop_table('pets')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index('idx_customers_phone')
        batch_op.drop_index('idx_customers_name')

    op.drop_table('customers')
    op.drop_table('cost_categories')
    # ### end Alembic commands ###
