"""add budgets table

Revision ID: 7dd7aae05221
Revises: 096466e69945
Create Date: 2026-05-21 21:35:08.284328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dd7aae05221'
down_revision: Union[str, Sequence[str], None] = '096466e69945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False, comment='预算类型：global/pet/category'),
    sa.Column('target_id', sa.String(length=50), nullable=True, comment='预算目标ID：pet_id或category_code，global时为null'),
    sa.Column('year', sa.Integer(), nullable=False, comment='预算年份'),
    sa.Column('month', sa.Integer(), nullable=False, comment='预算月份（1-12）'),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False, comment='预算金额'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'target_id', 'year', 'month', name='uk_budgets_unique'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index('idx_budgets_type_target', ['type', 'target_id'], unique=False)
        batch_op.create_index('idx_budgets_year_month', ['year', 'month'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index('idx_budgets_year_month')
        batch_op.drop_index('idx_budgets_type_target')

    op.drop_table('budgets')
    # ### end Alembic commands ###
